site_name: Calcium Imaging Analysis
site_description: Documentation for Calcium Imaging Analysis Tool
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_submodules: true
            filters: ["!^_"]
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav

nav:
  - Home: index.md
  - API Reference: reference/

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true 