TIME_COL = "Time (ms)"

BACKGROUND_FLUORESCENCE_ROI_1 = "ROI 1 (Average)"
BACKGROUND_FLUORESCENCE_ROI_2 = "ROI 2 (Average)"
BACKGROUND_FLUORESCENCE_ROI_3 = "ROI 3 (Average)"
BACKGROUND_FLUORESCENCE_ROIS = [
    BACKGROUND_FLUORESCENCE_ROI_1,
    BACKGROUND_FLUORESCENCE_ROI_2,
    BACKGROUND_FLUORESCENCE_ROI_3
]
